### ISSUE TITLE
Issue when remove aliases

### ISSUE THREAD

**Issue by equinusocio** [oivva/st-file-icons-extended#1]
By removing all `.tmPreferences` aliases all icons are not displayed. Do you mean other tmPreferences files?

> Remove syntax alias .tmPreferences files from your theme
Check the name of the each icon that you provide with the theme. They should be the same as in ICONS.md.

**Comment by oivva** [comment]
I mean only these: https://github.com/oivva/st-file-icons-extended/tree/master/preferences

With **Material Theme** everything is ok in the latest release, nothing to do :)

**Comment by equinusocio** [comment]
Oks!
PS: rebuilding the workspace fix the other issue.

**Comment by equinusocio** [comment]
@oivva So, the goal is to use only this centralized package to add the icons support? Right? We have to add here all other `tmPreferences` files?

**Comment by oivva** [comment]
Partially, this package is only for syntax aliases to the default ST packages (Gulpfile, Gruntfile & etc.). It means that if you want to set custom icon for the file which use the syntax from the default package, you should add alias here.

For example: 

Some `wow.json` uses default JSON syntax, but you want to add custom icon for it (such as NPM icon for  `package.json`), you should add support of this icon here.

For icons based on syntax scopes (not aliases to the default packages) I've created file icons dependency (see [pr](https://github.com/wbond/package_control_channel/pull/5716)), which maybe will be available later or will be published as package (it contains all preferences those currently stored in the theme).

The reason why we have two packages for the one goal is that this package may cause some problems for new users (they should know what they do).

**Comment by equinusocio** [comment]
Thanks. I will add instructions on the readme
